#!/usr/bin/env python
"""Generate the docs-site dataset catalog from $VSC_DATA_VO/shared/**/metadata.yaml.

Usage: python scripts/build_catalog.py
"""
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
SHARED_DIR = REPO_ROOT / "VSC_DATA_VO" / "shared"
OUT_DIR = REPO_ROOT / "docs-site" / "docs" / "datasets"


def category_of(metadata_path: Path) -> str:
    # .../shared/<category>/<dataset>/metadata.yaml
    return metadata_path.relative_to(SHARED_DIR).parts[0]


def render_dataset_page(meta: dict, category: str, rel_data_path: str) -> str:
    d = meta["dataset"]
    src = meta["source"]
    cov = meta["coverage"]
    contact = meta["contact"]

    lines = [
        f"# {d['name']}",
        "",
        f"*{d['long_name']}*",
        "",
        d["description"].strip(),
        "",
        "## Details",
        "",
        "| | |",
        "|---|---|",
        f"| **Category** | `{category}` |",
        f"| **Version** | {d.get('version', '-')} |",
        f"| **Provider** | {src['provider']} |",
        f"| **License** | {src['license']} |",
        f"| **Source URL** | {src['url'] or '-'} |",
        f"| **DOI** | {src.get('doi') or '-'} |",
        f"| **Spatial domain** | {cov['spatial']['domain']} |",
        f"| **Spatial resolution** | {cov['spatial']['resolution']} |",
        f"| **Temporal coverage** | {cov['temporal']['start']} to {cov['temporal']['end']} |",
        f"| **Frequency** | {cov['temporal']['frequency']} |",
        f"| **Contact** | {contact['name']} ({contact['email']}, {contact['vsc_username']}) |",
        f"| **Path** | `{rel_data_path}` |",
        "",
        "## Variables",
        "",
        "| short_name | standard_name | units |",
        "|---|---|---|",
    ]
    for v in meta["variables"]:
        lines.append(f"| `{v['short_name']}` | {v['standard_name']} | {v['units']} |")

    lines += ["", "## Processing history", ""]
    for h in meta["history"]:
        if "source" in h:
            lines.append(f"- **{h['date']}** — {h['description']} ([source]({h['source']}))")
        else:
            lines.append(f"- **{h['date']}** — {h['description']}")

    lines.append("")
    return "\n".join(lines)


def main():
    # For CI: if shared_dir doesn't exist, exit successfully
    if not SHARED_DIR.exists():
        print(f"Directory {SHARED_DIR} does not exist - skipping catalog build")
        return 0

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for old in OUT_DIR.glob("*.md"):
        if old.name != "index.md":
            old.unlink()

    metadata_files = sorted(SHARED_DIR.rglob("metadata.yaml"))
    if not metadata_files:
        print(f"no metadata.yaml files found under {SHARED_DIR}")
        return 0  # Not an error for CI

    by_category = {}
    for path in metadata_files:
        meta = yaml.safe_load(path.read_text(encoding="utf-8"))
        category = category_of(path)
        name = meta["dataset"]["name"]
        rel_data_path = str(path.parent.relative_to(REPO_ROOT)).replace("\\", "/")

        page = render_dataset_page(meta, category, rel_data_path)
        (OUT_DIR / f"{name}.md").write_text(page, encoding="utf-8")

        by_category.setdefault(category, []).append((name, meta["dataset"]["long_name"]))
        print(f"wrote datasets/{name}.md")

    index_lines = ["# Data catalog", "", "Auto-generated by `scripts/build_catalog.py` from every", "`metadata.yaml` under `VSC_DATA_VO/shared/`. Do not edit by hand.", ""]
    for category in sorted(by_category):
        index_lines.append(f"## {category}")
        index_lines.append("")
        for name, long_name in sorted(by_category[category]):
            index_lines.append(f"- [{name}]({name}.md) — {long_name}")
        index_lines.append("")
    (OUT_DIR / "index.md").write_text("\n".join(index_lines), encoding="utf-8")
    print("wrote datasets/index.md")

    return 0


if __name__ == "__main__":
    sys.exit(main())
